from pathlib import Path

import pandas as pd

from .agentic_eda import AgenticEDAOrchestrator
from .assessment.ai_readiness import AIReadinessEngine
from .assessment.eda import EDAEngine
from .assessment.eda_execution import EDAExecutor
from .assessment.eda_planner import EDAPlanner
from .assessment.engine import AssessmentEngine
from .assessment.profiler import DatasetProfiler
from .console_report import Report
from .fix.engine import FixEngine
from .models.agentic_eda_config import AgenticEDAConfig
from .models.agentic_eda_result import (
    AgenticEDAResult,
    FollowUpAction,
    PriorityFinding,
    UnresolvedQuestion,
    VisualisationRecommendation,
)
from .models.ai_readiness_report import AIReadinessReport
from .models.assessment_report import AssessmentReport
from .models.dataset_profile import DatasetProfile
from .models.eda_execution_result import (
    EDAExecutionResult,
    EDAExecutionStepResult,
)
from .models.eda_plan import EDAPlan, EDAPlanStep
from .models.eda_result import EDAResult
from .models.fix_config import FixConfig
from .models.fix_result import FixResult
from .models.ready_result import ReadyResult
from .prepare.engine import PrepareEngine

__version__ = "0.2.1"

__all__ = [
    "__version__",
    "AgenticEDAConfig",
    "AgenticEDAOrchestrator",
    "AgenticEDAResult",
    "AIReadinessEngine",
    "AIReadinessReport",
    "AssessmentEngine",
    "AssessmentReport",
    "DatasetProfiler",
    "DatasetProfile",
    "EDAEngine",
    "EDAExecutionResult",
    "EDAExecutionStepResult",
    "EDAExecutor",
    "EDAPlan",
    "EDAPlanner",
    "EDAPlanStep",
    "EDAResult",
    "FixConfig",
    "FixEngine",
    "FixResult",
    "FollowUpAction",
    "PrepareEngine",
    "PriorityFinding",
    "ReadyResult",
    "Report",
    "UnresolvedQuestion",
    "VisualisationRecommendation",
    "analysis_ready",
    "assess_ai_readiness",
    "assess",
    "eda",
    "execute_eda",
    "fix",
    "plan_eda",
    "prepare",
    "profile",
    "run_agentic_eda",
]


def profile(
    dataset: str | Path | pd.DataFrame,
) -> DatasetProfile:
    """
    Generate a structural profile for a dataset.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.

    Returns:
        A DatasetProfile containing structural dataset information.
    """
    profiler = DatasetProfiler()
    return profiler.profile(dataset)


def assess(
    dataset: str | Path | pd.DataFrame,
) -> AssessmentReport:
    """
    Assess the quality of a dataset.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.

    Returns:
        An AssessmentReport containing quality scores, validations, and
        recommendations.
    """
    engine = AssessmentEngine()
    return engine.assess(dataset)


def assess_ai_readiness(
    dataset: str | Path | pd.DataFrame,
) -> AIReadinessReport:
    """
    Assess whether a dataset is ready for AI-powered applications.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.

    Returns:
        An AIReadinessReport with AI suitability metrics and recommendations.
    """
    engine = AIReadinessEngine()
    return engine.assess(dataset)


def eda(
    dataset: str | Path | pd.DataFrame,
) -> EDAResult:
    """
    Generate a deterministic exploratory data analysis result.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.

    Returns:
        An EDAResult containing descriptive analysis and recommendations.
    """
    engine = EDAEngine()
    return engine.analyze(dataset)


def plan_eda(
    result: EDAResult,
) -> EDAPlan:
    """
    Build a deterministic follow-up analysis plan for an EDA result.

    Args:
        result: An EDAResult generated by :func:`eda`.

    Returns:
        An EDAPlan explaining every selected and skipped analysis step.
    """
    planner = EDAPlanner()
    return planner.plan(result)


def execute_eda(
    dataset: str | Path | pd.DataFrame,
    result: EDAResult | None = None,
    plan: EDAPlan | None = None,
) -> EDAExecutionResult:
    """
    Execute a deterministic EDA plan against a supported dataset.

    Missing EDA results and plans are generated automatically.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.
        result: Optional EDA result corresponding to the dataset.
        plan: Optional EDA plan corresponding to the result.

    Returns:
        An EDAExecutionResult containing step outputs and execution status.
    """
    executor = EDAExecutor()
    return executor.execute(
        dataset=dataset,
        result=result,
        plan=plan,
    )


def run_agentic_eda(
    dataset: str | Path | pd.DataFrame,
    config: AgenticEDAConfig | None = None,
) -> AgenticEDAResult:
    """
    Run the complete deterministic Agentic EDA workflow.

    The workflow understands the dataset, plans and executes applicable
    analyses, and generates traceable follow-up decisions without using an LLM.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.
        config: Optional deterministic thresholds and feature toggles.

    Returns:
        An AgenticEDAResult containing all workflow stages and recommendations.
    """
    orchestrator = AgenticEDAOrchestrator()
    return orchestrator.run(dataset=dataset, config=config)


def fix(
    dataset: str | Path | pd.DataFrame,
    config: FixConfig | None = None,
) -> FixResult:
    """
    Automatically clean a dataset.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.
        config: Optional configuration for the cleaning operation.

    Returns:
        A FixResult containing the cleaned DataFrame, before and after
        assessment reports, and applied fixes.
    """
    engine = FixEngine()
    return engine.fix(dataset, config)


def prepare(
    dataset: str | Path | pd.DataFrame,
) -> pd.DataFrame:
    """
    Prepare a dataset for downstream analytics or machine learning.

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.

    Returns:
        A prepared pandas DataFrame.
    """
    engine = PrepareEngine()
    return engine.prepare(dataset)


def analysis_ready(
    dataset: str | Path | pd.DataFrame,
    config: FixConfig | None = None,
) -> pd.DataFrame:
    """
    Clean and prepare a dataset for exploratory data analysis (EDA).

    Args:
        dataset: A pandas DataFrame or path to a supported dataset file.
        config: Optional configuration for the cleaning operation.

    Returns:
        A cleaned and prepared pandas DataFrame.
    """

    cleaned = fix(
        dataset,
        config=config,
    )

    engine = PrepareEngine()

    return engine.prepare(
        cleaned.dataset,
    )
