from pathlib import Path

from easydatafix.models.assessment_report import AssessmentReport


class MarkdownReport:
    """
    Exports an AssessmentReport as a Markdown report.
    """

    @staticmethod
    def export(
        report: AssessmentReport,
        output_file: str,
    ) -> None:

        lines: list[str] = []

        lines.append("# 🛠 Easy Data Fix Report")
        lines.append("")

        lines.append("## Dataset Information")
        lines.append("")
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(
            f"| File Name | {report.dataset_info.file_name} |"
        )
        lines.append(
            f"| Rows | {report.dataset_info.rows} |"
        )
        lines.append(
            f"| Columns | {report.dataset_info.columns} |"
        )
        lines.append(
            f"| Memory Usage | {report.dataset_info.memory_usage_bytes:,} Bytes |"
        )
        lines.append("")

        lines.append("## Overall Quality")
        lines.append("")
        lines.append(f"**Score:** {report.quality.score:.2f}")
        lines.append("")
        lines.append(f"**Grade:** {report.quality.grade}")
        lines.append("")

        lines.append("## Quality Dimensions")
        lines.append("")
        lines.append("| Metric | Score |")
        lines.append("|--------|------:|")
        lines.append(
            f"| Completeness | {report.quality_dimensions.completeness:.2f}% |"
        )
        lines.append(
            f"| Uniqueness | {report.quality_dimensions.uniqueness:.2f}% |"
        )
        lines.append(
            f"| Validity | {report.quality_dimensions.validity:.2f}% |"
        )
        lines.append(
            f"| Consistency | {report.quality_dimensions.consistency:.2f}% |"
        )
        lines.append(
            f"| Accuracy | {report.quality_dimensions.accuracy:.2f}% |"
        )
        lines.append(
            f"| Timeliness | {report.quality_dimensions.timeliness:.2f}% |"
        )
        lines.append(
            f"| **Overall** | **{report.quality_dimensions.overall:.2f}%** |"
        )
        lines.append("")

        lines.append("## Recommendations")
        lines.append("")

        if not report.recommendations:

            lines.append("- ✅ No recommendations.")

        else:

            for recommendation in report.recommendations:

                lines.append(
                    f"- **{recommendation.priority}** — {recommendation.title}"
                )

                lines.append(
                    f"  - Category: {recommendation.category}"
                )

                lines.append(
                    f"  - Auto Fix: {'Yes' if recommendation.auto_fix_available else 'No'}"
                )

                lines.append(
                    f"  - {recommendation.description}"
                )

                lines.append("")

        lines.append("## Validations")
        lines.append("")
        lines.append("| Rule | Column | Status |")
        lines.append("|------|--------|--------|")

        for validation in report.validations:

            status = "✅ PASS" if validation.passed else "❌ FAIL"

            lines.append(
                f"| {validation.rule} | {validation.column} | {status} |"
            )

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "*Generated by Easy Data Fix v0.1.0*"
        )

        Path(output_file).write_text(
            "\n".join(lines),
            encoding="utf-8",
        )
